package sistemas.operativos.proyecto2;

import java.util.Arrays;
import java.util.Date;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import sistemas.operativos.proyecto2.file.FileMetadata;
import sistemas.operativos.proyecto2.file.Folder;
import sistemas.operativos.proyecto2.lib.LinkedList;
import sistemas.operativos.proyecto2.simulator.Simulator;
import sistemas.operativos.proyecto2.simulator.Simulator.UserMode;
import sistemas.operativos.proyecto2.utils.Printer;

/**
 *
 * @author sebas
 */
public final class UIMain extends javax.swing.JFrame {
    public enum ElementType {
        FILE,
        FOLDER
    }
    
    private class TreeNodeSelection {
        public String name;
        public int size;
        public LinkedList<Integer> indices;
        public ElementType type;
        public long creation;
        public long lastModified;
        
        public TreeNodeSelection(String name, int size, LinkedList<Integer> indices, ElementType type, long creation, long lastModified) {
            this.name = name;
            this.size = size;
            this.indices = indices;
            this.type = type;
            this.creation = creation;
            this.lastModified = lastModified;
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(UIMain.class.getName());
    
    private final Simulator sim;
    
    private TreeNodeSelection selected;

    /**
     * Creates new form UIMain
     */
    public UIMain() {
        initComponents();
        initEvents();
        
        this.sim = new Simulator();
        
        Folder rootStart = this.sim.getCurrentFolder();
        this.selected = new TreeNodeSelection(rootStart.getName(), 0, null, ElementType.FOLDER, rootStart.getCreationTime(), rootStart.getLastModifiedTime());
        updateSelectedElement();
        
        this.sim.setMode(UserMode.USER);
        updateMode();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminButton = new javax.swing.JRadioButton();
        userButton = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fileName = new javax.swing.JTextField();
        fileSize = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fileButton = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        folderName = new javax.swing.JTextField();
        folderButton = new javax.swing.JToggleButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        elementSize = new javax.swing.JLabel();
        elementNameInput = new javax.swing.JTextField();
        elementName = new javax.swing.JLabel();
        elementSizeInput = new javax.swing.JTextField();
        elementName1 = new javax.swing.JLabel();
        elementTypeInput = new javax.swing.JTextField();
        elementName2 = new javax.swing.JLabel();
        elementCreatedInput = new javax.swing.JTextField();
        elementName3 = new javax.swing.JLabel();
        elementModifiedInput = new javax.swing.JTextField();
        elementName4 = new javax.swing.JLabel();
        elementIndicesInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        explorerJTree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 34, 34));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modo de Uso");

        adminButton.setBackground(new java.awt.Color(51, 51, 51));
        modeGroup.add(adminButton);
        adminButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(255, 255, 255));
        adminButton.setText("Admin");
        adminButton.setFocusPainted(false);
        adminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminButtonActionPerformed(evt);
            }
        });

        userButton.setBackground(new java.awt.Color(51, 51, 51));
        modeGroup.add(userButton);
        userButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userButton.setForeground(new java.awt.Color(255, 255, 255));
        userButton.setSelected(true);
        userButton.setText("Usuario");
        userButton.setFocusPainted(false);
        userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(adminButton)
                        .addGap(18, 18, 18)
                        .addComponent(userButton))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminButton)
                    .addComponent(userButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Archivo (Carpeta Actual)");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre");

        fileName.setBackground(new java.awt.Color(51, 51, 51));
        fileName.setForeground(new java.awt.Color(255, 255, 255));
        fileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileNameActionPerformed(evt);
            }
        });

        fileSize.setBackground(new java.awt.Color(51, 51, 51));
        fileSize.setForeground(new java.awt.Color(255, 255, 255));
        fileSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSizeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tamaño (bloques)");

        fileButton.setBackground(new java.awt.Color(51, 51, 51));
        fileButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fileButton.setForeground(new java.awt.Color(255, 255, 255));
        fileButton.setText("Crear Archivo");
        fileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fileButton.setFocusPainted(false);
        fileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileName))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileSize, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(fileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fileSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fileButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Carpeta (Carpeta Actual)");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre");

        folderName.setBackground(new java.awt.Color(51, 51, 51));
        folderName.setForeground(new java.awt.Color(255, 255, 255));
        folderName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderNameActionPerformed(evt);
            }
        });

        folderButton.setBackground(new java.awt.Color(51, 51, 51));
        folderButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        folderButton.setForeground(new java.awt.Color(255, 255, 255));
        folderButton.setText("Crear Carpeta");
        folderButton.setFocusPainted(false);
        folderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 69, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(folderName))
                    .addComponent(folderButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(folderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(folderButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(102, 102, 102));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Elemento Actual");

        elementSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elementSize.setForeground(new java.awt.Color(255, 255, 255));
        elementSize.setText("Tamaño (bloques)");

        elementNameInput.setBackground(new java.awt.Color(51, 51, 51));
        elementNameInput.setForeground(new java.awt.Color(255, 255, 255));
        elementNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementNameInputActionPerformed(evt);
            }
        });

        elementName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elementName.setForeground(new java.awt.Color(255, 255, 255));
        elementName.setText("Nombre");

        elementSizeInput.setBackground(new java.awt.Color(51, 51, 51));
        elementSizeInput.setForeground(new java.awt.Color(255, 255, 255));
        elementSizeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementSizeInputActionPerformed(evt);
            }
        });

        elementName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elementName1.setForeground(new java.awt.Color(255, 255, 255));
        elementName1.setText("Tipo de elemento");

        elementTypeInput.setBackground(new java.awt.Color(51, 51, 51));
        elementTypeInput.setForeground(new java.awt.Color(255, 255, 255));
        elementTypeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementTypeInputActionPerformed(evt);
            }
        });

        elementName2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elementName2.setForeground(new java.awt.Color(255, 255, 255));
        elementName2.setText("Creado");

        elementCreatedInput.setBackground(new java.awt.Color(51, 51, 51));
        elementCreatedInput.setForeground(new java.awt.Color(255, 255, 255));
        elementCreatedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementCreatedInputActionPerformed(evt);
            }
        });

        elementName3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elementName3.setForeground(new java.awt.Color(255, 255, 255));
        elementName3.setText("Editado");

        elementModifiedInput.setBackground(new java.awt.Color(51, 51, 51));
        elementModifiedInput.setForeground(new java.awt.Color(255, 255, 255));
        elementModifiedInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementModifiedInputActionPerformed(evt);
            }
        });

        elementName4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        elementName4.setForeground(new java.awt.Color(255, 255, 255));
        elementName4.setText("Índices");

        elementIndicesInput.setBackground(new java.awt.Color(51, 51, 51));
        elementIndicesInput.setForeground(new java.awt.Color(255, 255, 255));
        elementIndicesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elementIndicesInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(elementName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(elementNameInput))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(elementName1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementTypeInput))
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(elementSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(elementName2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementCreatedInput))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(elementName3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementModifiedInput))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(elementName4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementIndicesInput)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementName)
                    .addComponent(elementNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementSize)
                    .addComponent(elementSizeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementName4)
                    .addComponent(elementIndicesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementName1)
                    .addComponent(elementTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementName2)
                    .addComponent(elementCreatedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(elementName3)
                    .addComponent(elementModifiedInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        explorerJTree.setBackground(new java.awt.Color(255, 255, 255));
        explorerJTree.setForeground(new java.awt.Color(51, 51, 51));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        explorerJTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(explorerJTree);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminButtonActionPerformed
        // TODO add your handling code here:
        if (adminButton.isSelected()) {
            this.sim.setMode(UserMode.ADMIN);
            updateMode();
        }
    }//GEN-LAST:event_adminButtonActionPerformed

    private void userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userButtonActionPerformed
        // TODO add your handling code here:
        if (userButton.isSelected()) {
            this.sim.setMode(UserMode.USER);
            updateMode();
        }
    }//GEN-LAST:event_userButtonActionPerformed

    private void fileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileNameActionPerformed

    private void fileSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileSizeActionPerformed

    private void folderNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folderNameActionPerformed

    private void fileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileButtonActionPerformed
        // TODO add your handling code here:
        createFile();
    }//GEN-LAST:event_fileButtonActionPerformed

    private void folderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folderButtonActionPerformed
        // TODO add your handling code here:
        createFolder();
    }//GEN-LAST:event_folderButtonActionPerformed

    private void elementNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementNameInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementNameInputActionPerformed

    private void elementSizeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementSizeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementSizeInputActionPerformed

    private void elementTypeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementTypeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementTypeInputActionPerformed

    private void elementCreatedInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementCreatedInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementCreatedInputActionPerformed

    private void elementModifiedInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementModifiedInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementModifiedInputActionPerformed

    private void elementIndicesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elementIndicesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elementIndicesInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new UIMain().setVisible(true));
    }
    
    /*
     *   Crear archivos y carpetas
     */
    
    public void createFile() {
        String name = fileName.getText().trim();
        String sizeStr = fileSize.getText().trim();

        if (name.isEmpty() || sizeStr.isEmpty()) { return; }

        try {
            int size = Integer.parseInt(sizeStr);
            sim.writeFile(name, size);
            updateJTree();
        } catch (NumberFormatException ex) {
            System.out.println(ex);
        }
    };
    
    public void createFolder() {
        String name = folderName.getText().trim();
        if (name.isEmpty()) { return; }
        sim.createFolder(name);
        updateJTree();
    }
    
    /*
     *   Manipulación de JTree
     */
    
    private void addFile(DefaultMutableTreeNode node, FileMetadata reg) {
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(reg.getFileName());
        
        newNode.setAllowsChildren(false);
        
        node.add(newNode);
    }
    
    private void addFolder(DefaultMutableTreeNode node, Folder reg) {
        DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(reg.getName());
        
        newNode.setAllowsChildren(true);
        
        LinkedList<Folder> folders = reg.getSubfolders();
        LinkedList<FileMetadata> files = reg.getFiles();
        
        for (int i = 0; i < folders.size(); i++) {
            addFolder(newNode, folders.get(i));
        }
        
        for (int i = 0; i < files.size(); i++) {
            addFile(newNode, files.get(i));
        }
        
        node.add(newNode);
    }
    
    /*
     *   Updates
     */
    
    private void updateJTree() {
        DefaultTreeModel model = (DefaultTreeModel) explorerJTree.getModel();
        DefaultMutableTreeNode rootFolder = (DefaultMutableTreeNode)model.getRoot();
        
        rootFolder.removeAllChildren();
        
        LinkedList<Folder> folders = this.sim.rootFolder.getSubfolders();
        LinkedList<FileMetadata> files = this.sim.rootFolder.getFiles();
        
        for (int i = 0; i < folders.size(); i++) {
            addFolder(rootFolder, folders.get(i));
        }
        
        for (int i = 0; i < files.size(); i++) {
            addFile(rootFolder, files.get(i));
        }
        
        model.reload(rootFolder);
        
        this.sim.currentToRoot();
    }
    
    public final void updateMode() {
        UserMode mode = this.sim.getMode();
        
        switch(mode) {
            case ADMIN -> {
                fileName.setEnabled(true);
                fileSize.setEnabled(true);
                folderName.setEnabled(true);
                
                fileButton.setEnabled(true);
                folderButton.setEnabled(true);
            }
            case USER -> {
                fileName.setEnabled(false);
                fileSize.setEnabled(false);
                folderName.setEnabled(false);
                
                fileButton.setEnabled(false);
                folderButton.setEnabled(false);
            }
            default -> {
                fileName.setEnabled(false);
                fileSize.setEnabled(false);
                folderName.setEnabled(false);
                
                fileButton.setEnabled(false);
                folderButton.setEnabled(false);
            }
        }
    }
    
    public void updateSelectedElement() {
        this.elementNameInput.setText(this.selected.name);
        this.elementSizeInput.setText(String.valueOf(this.selected.size));
        
        if (this.selected.indices != null) {
            this.elementIndicesInput.setText(this.selected.indices.toString());
        } else {
            this.elementIndicesInput.setText("No hay indices");
        }
        
        switch(this.selected.type) {
            case ElementType.FILE -> {
                this.elementTypeInput.setText("Archivo");
            }
            case ElementType.FOLDER -> {
                this.elementTypeInput.setText("Carpeta");
            }
            default -> {
                this.elementTypeInput.setText("Desconocido");
            }
        }
                
        this.elementCreatedInput.setText(new Date(this.selected.creation).toString());
        this.elementModifiedInput.setText(new Date(this.selected.lastModified).toString());
    }
    
    /*
     *   Eventos
     */
    
    public void initEvents() {
        
        // JTree Event
        explorerJTree.getSelectionModel().addTreeSelectionListener((TreeSelectionEvent e) -> {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) explorerJTree.getLastSelectedPathComponent();
            
            if (selectedNode != null) {
                int maxPathLength = selectedNode.getUserObjectPath().length;
                Folder selectionFolder = this.sim.rootFolder;
                FileMetadata selectionFile = null;
                this.sim.currentToRoot();
                
                if (selectedNode.getAllowsChildren()) {                    
                    for (int i = 1; i < maxPathLength; i++) {
                        selectionFolder = this.sim.getFolder(selectedNode.getUserObjectPath()[i].toString()).getCurrentFolder();
                    }
                    
                    this.selected = new TreeNodeSelection(selectionFolder.getName(), 0, null, ElementType.FOLDER, selectionFolder.getCreationTime(), selectionFolder.getLastModifiedTime());
                } else {
                    for (int i = 1; i < maxPathLength - 1; i++) {
                        selectionFolder = this.sim.getFolder(selectedNode.getUserObjectPath()[i].toString()).getCurrentFolder();
                    }
                    
                    selectionFile = selectionFolder.getFile(selectedNode.getUserObjectPath()[maxPathLength - 1].toString());
                    
                    this.selected = new TreeNodeSelection(selectionFile.getFileName(), selectionFile.getFileSize(), selectionFile.getBlockIndices(), ElementType.FILE, selectionFile.getCreationTime(), selectionFile.getLastModifiedTime());
                }
                
                updateSelectedElement();
                
                Printer.print(selectedNode.getUserObject().toString());
                Printer.print(Arrays.toString(selectedNode.getUserObjectPath()));
                Printer.print(selectedNode.getAllowsChildren()); // Chequea si puede tener hijos o no (si es carpeta o archivo)
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminButton;
    private javax.swing.JTextField elementCreatedInput;
    private javax.swing.JTextField elementIndicesInput;
    private javax.swing.JTextField elementModifiedInput;
    private javax.swing.JLabel elementName;
    private javax.swing.JLabel elementName1;
    private javax.swing.JLabel elementName2;
    private javax.swing.JLabel elementName3;
    private javax.swing.JLabel elementName4;
    private javax.swing.JTextField elementNameInput;
    private javax.swing.JLabel elementSize;
    private javax.swing.JTextField elementSizeInput;
    private javax.swing.JTextField elementTypeInput;
    private javax.swing.JTree explorerJTree;
    private javax.swing.JToggleButton fileButton;
    private javax.swing.JTextField fileName;
    private javax.swing.JTextField fileSize;
    private javax.swing.JToggleButton folderButton;
    private javax.swing.JTextField folderName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup modeGroup;
    private javax.swing.JRadioButton userButton;
    // End of variables declaration//GEN-END:variables
}
